# Generated by Django 6.1.1 on 2026-09-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appretrut1', '0002_utili_delete_candidat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utili',
            name='motdepasse',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
