# Generated by Django 6.1.1 on 2026-09-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appretrut1', '0003_alter_utili_motdepasse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utili',
            name='competence',
        ),
        migrations.RemoveField(
            model_name='utili',
            name='domaine',
        ),
        migrations.RemoveField(
            model_name='utili',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='utili',
            name='metier',
        ),
        migrations.RemoveField(
            model_name='utili',
            name='nationalite',
        ),
        migrations.RemoveField(
            model_name='utili',
            name='niveau_etudes',
        ),
        migrations.RemoveField(
            model_name='utili',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='utili',
            name='sexe',
        ),
        migrations.AlterField(
            model_name='utili',
            name='motdepasse',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='utili',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
