# Generated by Django 6.1.1 on 2026-09-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appretrut1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='utili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telephone', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('sexe', models.CharField(max_length=20)),
                ('metier', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('niveau_etudes', models.CharField(max_length=100)),
                ('nationalite', models.CharField(max_length=100)),
                ('domaine', models.CharField(max_length=150)),
                ('motdepasse', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profils/')),
                ('competence', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='candidat',
        ),
    ]
